pipeline {
   agent any
   
   environment {
      DEMO='1.3'
   }

   stages {
      stage('Checkout') {
            steps {
                // Checkout the repository into the workspace
                checkout([$class: 'GitSCM', branches: [[name: 'main']], userRemoteConfigs: [[url: 'https://github.com/mrobergl/using-declarative-jenkins-pipelines.git']]])
            }
        }
      stage('stage-1') {
         steps {
            echo "This is build number $BUILD_NUMBER of demo $DEMO"
            sh '''
               echo "Using a multi-line shell step"
               git checkout origin/main -- 02/demos/demo1/1.3/test.sh
               chmod +x test.sh
               ./test.sh
            '''
         }
      }
   }
}
